### PR TITLE
Handle array properties correctly (next branch)

### PR DESCRIPTION
**Pull request by usu**
Same as #243 but for `next` branch

### CODE REVIEW

**Review by carlobeltrame — APPROVED** [review]
Thanks!

**Comment by carlobeltrame** [comment]
hal-json-vuex 2.0.0-alpha.11 is published.

**Comment by usu** [comment]
> hal-json-vuex 2.0.0-alpha.11 is published.

@carlobeltrame Can you have a look if the package was properly built before publishing 2.0.0-alpha.11? I struggle to get things working when downloading the package via npm. When building locally and adding via yalc, everything works as it should.

First I thought it could be a caching issue, but removed cache and redownloaded from npm multiple times - still doesn't work.

**Comment by carlobeltrame** [comment]
Hmmm good question. I thought the publishing tool `np` should build automatically before releasing, but looks like it doesn't. I just published alpha.12, can you try with that?
I'll have to show you soon how to release so you can also do it whenever you need it.

**Comment by usu** [comment]
Yes, much better 😃 
PR is here: https://github.com/ecamp/ecamp3/pull/2337

**Pull request merged**
